FROM python:3.12

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && pip install -U langchain_community && pip install cryptography

COPY . .

CMD [ "python", "cmd/aiservice/main.py" ]