# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pkg.proto.aiservice.v1.aiservice_pb2 as aiservice__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in aiservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.generateTitleAndTag = channel.unary_unary(
                '/v1.AIService/generateTitleAndTag',
                request_serializer=aiservice__pb2.PromptContentRequest.SerializeToString,
                response_deserializer=aiservice__pb2.GenerateTitleAndTagResponse.FromString,
                _registered_method=True)
        self.polishContent = channel.unary_stream(
                '/v1.AIService/polishContent',
                request_serializer=aiservice__pb2.PromptContentRequest.SerializeToString,
                response_deserializer=aiservice__pb2.PolishContentResponse.FromString,
                _registered_method=True)
        self.searchPosts = channel.unary_unary(
                '/v1.AIService/searchPosts',
                request_serializer=aiservice__pb2.PromptRequest.SerializeToString,
                response_deserializer=aiservice__pb2.SearchPostsResponse.FromString,
                _registered_method=True)
        self.summaryContent = channel.unary_stream(
                '/v1.AIService/summaryContent',
                request_serializer=aiservice__pb2.ContentRequest.SerializeToString,
                response_deserializer=aiservice__pb2.SummaryContentResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def generateTitleAndTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def polishContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def summaryContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'generateTitleAndTag': grpc.unary_unary_rpc_method_handler(
                    servicer.generateTitleAndTag,
                    request_deserializer=aiservice__pb2.PromptContentRequest.FromString,
                    response_serializer=aiservice__pb2.GenerateTitleAndTagResponse.SerializeToString,
            ),
            'polishContent': grpc.unary_stream_rpc_method_handler(
                    servicer.polishContent,
                    request_deserializer=aiservice__pb2.PromptContentRequest.FromString,
                    response_serializer=aiservice__pb2.PolishContentResponse.SerializeToString,
            ),
            'searchPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.searchPosts,
                    request_deserializer=aiservice__pb2.PromptRequest.FromString,
                    response_serializer=aiservice__pb2.SearchPostsResponse.SerializeToString,
            ),
            'summaryContent': grpc.unary_stream_rpc_method_handler(
                    servicer.summaryContent,
                    request_deserializer=aiservice__pb2.ContentRequest.FromString,
                    response_serializer=aiservice__pb2.SummaryContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def generateTitleAndTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AIService/generateTitleAndTag',
            aiservice__pb2.PromptContentRequest.SerializeToString,
            aiservice__pb2.GenerateTitleAndTagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def polishContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/v1.AIService/polishContent',
            aiservice__pb2.PromptContentRequest.SerializeToString,
            aiservice__pb2.PolishContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.AIService/searchPosts',
            aiservice__pb2.PromptRequest.SerializeToString,
            aiservice__pb2.SearchPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def summaryContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/v1.AIService/summaryContent',
            aiservice__pb2.ContentRequest.SerializeToString,
            aiservice__pb2.SummaryContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
