# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aiservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aiservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61iservice.proto\"0\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07postIds\x18\x02 \x03(\t\":\n\x13SearchPostsResponse\x12\x0f\n\x07postIds\x18\x01 \x03(\t\x12\x12\n\nevaluation\x18\x02 \x01(\t\"\'\n\x14SummaryPostsResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"7\n\x14PromptContentRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\":\n\x1bGenerateTitleAndTagResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\"-\n\x15PolishContentResponse\x12\x14\n\x0c\x63ontentChunk\x18\x01 \x01(\t2Y\n\tAIService\x12L\n\x13GenerateTitleAndTag\x12\x15.PromptContentRequest\x1a\x1c.GenerateTitleAndTagResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMPTREQUEST']._serialized_start=19
  _globals['_PROMPTREQUEST']._serialized_end=67
  _globals['_SEARCHPOSTSRESPONSE']._serialized_start=69
  _globals['_SEARCHPOSTSRESPONSE']._serialized_end=127
  _globals['_SUMMARYPOSTSRESPONSE']._serialized_start=129
  _globals['_SUMMARYPOSTSRESPONSE']._serialized_end=168
  _globals['_PROMPTCONTENTREQUEST']._serialized_start=170
  _globals['_PROMPTCONTENTREQUEST']._serialized_end=225
  _globals['_GENERATETITLEANDTAGRESPONSE']._serialized_start=227
  _globals['_GENERATETITLEANDTAGRESPONSE']._serialized_end=285
  _globals['_POLISHCONTENTRESPONSE']._serialized_start=287
  _globals['_POLISHCONTENTRESPONSE']._serialized_end=332
  _globals['_AISERVICE']._serialized_start=334
  _globals['_AISERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
