"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PromptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    POSTIDS_FIELD_NUMBER: builtins.int
    prompt: builtins.str
    @property
    def postIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        prompt: builtins.str = ...,
        postIds: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["postIds", b"postIds", "prompt", b"prompt"]) -> None: ...

global___PromptRequest = PromptRequest

@typing.final
class SearchPostsResponse(google.protobuf.message.Message):
    """如果包含多轮搜索，可能是比较耗时的操作，可以借助go的协程来完成多轮搜索并合并，不需要agent直接操作？
    1\\给出一个搜索语句，搜索其title和abstract（或者只搜索title），筛选出一定条数内容。
    2\\查看title和abstract，筛选出符合条件的内容
    3\\生成筛选评价，以及筛选结果。
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSTIDS_FIELD_NUMBER: builtins.int
    EVALUATION_FIELD_NUMBER: builtins.int
    evaluation: builtins.str
    """给出一个summary说明ai对搜索可行性及结果可信程度的评估。"""
    @property
    def postIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        postIds: collections.abc.Iterable[builtins.str] | None = ...,
        evaluation: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["evaluation", b"evaluation", "postIds", b"postIds"]) -> None: ...

global___SearchPostsResponse = SearchPostsResponse

@typing.final
class SummaryPostsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    content: builtins.str
    def __init__(
        self,
        *,
        content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content"]) -> None: ...

global___SummaryPostsResponse = SummaryPostsResponse

@typing.final
class PromptContentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    prompt: builtins.str
    content: builtins.str
    def __init__(
        self,
        *,
        prompt: builtins.str = ...,
        content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "prompt", b"prompt"]) -> None: ...

global___PromptContentRequest = PromptContentRequest

@typing.final
class GenerateTitleAndTagResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TITLE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    title: builtins.str
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tags", b"tags", "title", b"title"]) -> None: ...

global___GenerateTitleAndTagResponse = GenerateTitleAndTagResponse

@typing.final
class PolishContentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENTCHUNK_FIELD_NUMBER: builtins.int
    contentChunk: builtins.str
    def __init__(
        self,
        *,
        contentChunk: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contentChunk", b"contentChunk"]) -> None: ...

global___PolishContentResponse = PolishContentResponse
