"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PromptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    prompt: builtins.str
    def __init__(
        self,
        *,
        prompt: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["prompt", b"prompt"]) -> None: ...

global___PromptRequest = PromptRequest

@typing.final
class SearchPostsResponse(google.protobuf.message.Message):
    """message SummaryPostsRequest{
        string prompt = 1;
        repeated string ids = 2;
    }
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDS_FIELD_NUMBER: builtins.int
    EVALUATION_FIELD_NUMBER: builtins.int
    evaluation: builtins.str
    @property
    def ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        ids: collections.abc.Iterable[builtins.str] | None = ...,
        evaluation: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["evaluation", b"evaluation", "ids", b"ids"]) -> None: ...

global___SearchPostsResponse = SearchPostsResponse

@typing.final
class ContentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    content: builtins.str
    def __init__(
        self,
        *,
        content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content"]) -> None: ...

global___ContentRequest = ContentRequest

@typing.final
class PromptContentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    prompt: builtins.str
    content: builtins.str
    def __init__(
        self,
        *,
        prompt: builtins.str = ...,
        content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "prompt", b"prompt"]) -> None: ...

global___PromptContentRequest = PromptContentRequest

@typing.final
class GenerateTitleAndTagResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TITLE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    title: builtins.str
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tags", b"tags", "title", b"title"]) -> None: ...

global___GenerateTitleAndTagResponse = GenerateTitleAndTagResponse

@typing.final
class PolishContentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENTCHUNK_FIELD_NUMBER: builtins.int
    contentChunk: builtins.str
    def __init__(
        self,
        *,
        contentChunk: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contentChunk", b"contentChunk"]) -> None: ...

global___PolishContentResponse = PolishContentResponse

@typing.final
class SummaryContentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENTCHUNK_FIELD_NUMBER: builtins.int
    contentChunk: builtins.str
    def __init__(
        self,
        *,
        contentChunk: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contentChunk", b"contentChunk"]) -> None: ...

global___SummaryContentResponse = SummaryContentResponse
